spring.datasource.url=jdbc:postgresql://localhost:5432/test
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Spring Security Authentication Type Configuration
# Options: inmemory, jdbc, custom
security.auth.type=inmemory

# Spring Security Authentication Provider Configuration
# Options: default, custom
security.provider.type=default

# Spring Security Authentication Manager Configuration
# Options: default, custom
security.manager.type=default

# Spring Security Password Encoder Configuration
# Options: bcrypt, sha2, noop
security.encoder.type=bcrypt



